# Generated by Django 4.0.5 on 2022-06-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adress',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
