# Generated by Django 4.0.5 on 2022-06-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.item'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ManyToManyField(through='orders.OrderItem', to='users.user'),
        ),
    ]
