# Generated by Django 4.0.5 on 2022-06-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_imgaeurl_url_alter_item_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(default='', max_length=200),
        ),
    ]
