# Generated by Django 4.0.5 on 2022-06-24 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_content_alter_product_manual_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImgaeUrl',
            new_name='ImageUrl',
        ),
    ]
