# Generated by Django 4.0.5 on 2022-06-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_imgaeurl_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
